// generate with /auth/test
export const authToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZDZjN2QzYzM0ZDVhM2M2OGMyZjU3MCIsInJvbGUiOiJDTEkiLCJpYXQiOjE3NDIzMjQ1MzcsImV4cCI6MTc0MjQxMDkzN30.SYCzQhSOMTErlzd3Q8ShtItqW9wsbhY46gLQ4DPvgjU';
