// generate with /auth/test
export const authToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZDZjN2QzYzM0ZDVhM2M2OGMyZjU3MCIsInJvbGUiOiJDTEkiLCJpYXQiOjE3NDIxMjk1MzgsImV4cCI6MTc0MjIxNTkzOH0.eMkQ92_GGGZ8E1Jk7noqh3AC4EHJXAzHkGGbjzZnSrk';
