// generate with /auth/test
export const authToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZDZjN2QzYzM0ZDVhM2M2OGMyZjU3MCIsInJvbGUiOiJDTEkiLCJpYXQiOjE3NDIyMzc1MDUsImV4cCI6MTc0MjMyMzkwNX0.oT91_lGELE6pzQMAtiYtTQnkAHNo2J7msWzwwxOf1eE';
